# Generated by Django 6.0.6 on 2026-06-27 00:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(help_text='Ej: Bancolombia, Nequi, Efectivo', max_length=100)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo disponible', max_digits=15)),
                ('tipo_cuenta', models.CharField(choices=[('AHORRO', 'Ahorro'), ('CORRIENTE', 'Corriente'), ('EFECTIVO', 'Efectivo')], default='AHORRO', max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Tarjeta Visa, Crédito de Estudio', max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Saldo total pendiente', max_digits=15)),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='Tasa de interés (%)', max_digits=5)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, help_text='Valor aproximado de la cuota mensual', max_digits=15)),
                ('fecha_proximo_pago', models.DateField(help_text='Fecha límite de pago más cercana')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Viaje a Europa, Fondo de Emergencia', max_length=100)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, help_text='Meta total a ahorrar', max_digits=15)),
                ('monto_ahorrado_actual', models.DecimalField(decimal_places=2, default=0.0, help_text='Ahorrado acumulado', max_digits=15)),
                ('fecha_limite', models.DateField(help_text='Fecha máxima para alcanzar la meta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=15)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('GASTO', 'Gasto')], max_length=10)),
                ('categoria', models.CharField(help_text='Ej: Comida, Transporte, Salario, Ocio', max_length=50)),
                ('fecha', models.DateTimeField(help_text='Fecha del movimiento')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.cuenta')),
                ('deuda', models.ForeignKey(blank=True, help_text='Vincular a abonos a deudas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.deuda')),
                ('meta_ahorro', models.ForeignKey(blank=True, help_text='Vincular a un bolsillo de ahorro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='core.metaahorro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
