# Generated by Django 6.0.6 on 2026-06-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha de finalización total del crédito o deuda', null=True),
        ),
    ]
