# Generated by Django 6.0.6 on 2026-06-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deuda_fecha_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompraDiferida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(help_text='Nombre del artículo', max_length=150)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad a comprar')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=15)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo total: cantidad x precio unitario', max_digits=15)),
                ('fecha_planeada', models.DateField(help_text='Fecha planeada para realizar la compra')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPRADO', 'Comprado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_diferidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Categoría de gasto, ej: Comida, Transporte, Ocio', max_length=50)),
                ('monto_limite', models.DecimalField(decimal_places=2, help_text='Límite máximo de gasto mensual', max_digits=15)),
                ('mes', models.IntegerField(help_text='Mes del presupuesto (1-12)')),
                ('anio', models.IntegerField(help_text='Año del presupuesto (ej: 2026)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria', 'mes', 'anio')},
            },
        ),
    ]
