# Generated by Django 6.0.6 on 2026-06-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemcompradiferida_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompradiferida',
            name='fecha_planeada',
            field=models.DateField(blank=True, help_text='Fecha planeada para realizar la compra', null=True),
        ),
        migrations.AlterField(
            model_name='itemcompradiferida',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_diferidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la lista (ej: Comida familiar)', max_length=150)),
                ('fecha_planeada', models.DateField(help_text='Fecha planeada para realizar las compras de esta lista')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPRADO', 'Comprado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('categoria_asociada', models.CharField(blank=True, help_text='Categoría de presupuesto vinculada a esta lista para evaluación de gastos (ej: Comida)', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemcompradiferida',
            name='lista_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.listacompras'),
        ),
    ]
