# Generated by Django 6.0.6 on 2026-06-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_itemcompradiferida_fecha_planeada_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
