# Generated by Django 6.0.6 on 2026-06-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcompradiferida',
            name='lista_compras',
        ),
        migrations.DeleteModel(
            name='ListaCompras',
        ),
    ]
