# Generated by Django 6.0.6 on 2026-06-29 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_itemcompradiferida_lista_compras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto de compra', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o contexto del proyecto', null=True)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor o lugar de compra', max_length=150, null=True)),
                ('fecha_ejecucion', models.DateField(help_text='Fecha planeada para ejecutar el proyecto')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COTIZADO', 'Cotizado'), ('COMPRADO', 'Comprado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas y observaciones personalizadas', null=True)),
                ('etiquetas', models.CharField(blank=True, help_text='Clasificación o tags (ej: #Hogar)', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_compra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(help_text='Nombre del artículo o producto', max_length=150)),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad del producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=15)),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Costo total de la línea', max_digits=15)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('nota', models.CharField(blank=True, help_text='Nota del producto (ej: color o modelo)', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.proyectocompra')),
            ],
        ),
    ]
