# Generated by Django 6.0.6 on 2026-06-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_proyectocompra_itemproyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCompraDiferida',
        ),
    ]
